title:              "어쩌다 장업계 마케터"
tagline:            "막연히 마케터가 되고싶다면, 혹은 장업계에서 일하고싶다면?"
email:              "shunaem2@gmail.com"
linkedin:           "https://www.linkedin.com/in/%EC%9C%A4%EC%88%98-%EC%86%A1-a834741b1/"
description:        "철이 없었죠, 화장품이 좋아서 취업을 했다는게"
author:             "슈냄"
baseurl:            "/"
url:                "https://shunaem.com"
locale:             "ko_KR"
thumbnail:          "img/blogthumbnail.png"

# Social Profiles


# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: shunaem-com
