title:              "어쩌다 장업계 마케터"
tagline:            "블로그 슬로건"
email:              "shunaem2@gmail.com"
description:        "블로그 설명"
author:             "작성자 이름"
baseurl:            "/"
url:                "https://shunaem.com"
locale:             "ko_KR"
thumbnail:          "img/blogthumbnail.png"

# Social Profiles


# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
